- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Apache insallation
    yum:
      name: httpd
      state: present
  - name: Start the apache service
    service:
      name: httpd
      state: started
  - name: Deploy the code
    copy:
      src: /home/ec2-user/index.html
      dest: /var/www/html/index.html
      