- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Install all packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - mysql
      - unzip
      - http_present
