- hosts: all
  remote_user: ec2-user
  become: yes
  vars_files:
    myconfig.yaml
  tasks:
  - name: Testing echo command
    debug:
      msg: My username is {{ uname }} and my password is {{ pass }}



ansible-vault encrypt myconfig.yaml